### ISSUE TITLE
How to configure video layout using opentok-react

### ISSUE THREAD

**Issue by sfmendes91** [opentok/opentok-react#102]
Imagine if we have 1, 2, 3 or more subscribers.

How can i change the layout of opentok using this library?  Where do i define a default layout for this? Or how can i customize ?

**Comment by enricop89** [comment]
You can use [OTStreams](https://github.com/opentok/opentok-react#otstreams-component) and then apply CSS rules using className or Style property.

I can suggest using this library as a starting point: https://github.com/aullman/opentok-layout-js
for video layout

**Comment by sfmendes91** [comment]
@enricop89 i will make changes like that then.

Thanks a lot for the comment :)
