### ISSUE TITLE
In publisher properties facing mode is not working

### ISSUE THREAD

**Issue by mawais78** [opentok/opentok-react#103]
Hi,

I'm using this package on website and on chrome and other browsers the properties of Publisher facingMode is not working and it is not using back camera.

What is the solution?
Here is my code

```
constructor(props) {
        super(props)
        this.publisherProperties = {
            facingMode: 'environment'
          };
    }

<OTSession apiKey={apiKey} sessionId={sessionId} token={token}>
                <OTPublisher
                    properties={this.publisherProperties}
                />
                <OTStreams>
                <OTSubscriber />
                </OTStreams>
                </OTSession>
```

**Comment by enricop89** [comment]
@mawais78 Hey, facingMode is valid only when you run the app on mobile browsers. The laptop doesn't have any back camera. Have a look here: https://tokbox.com/developer/sdks/js/reference/OT.html

I tested the code on mobile and it works.
