### ISSUE TITLE
Opentok intermittent failure on IOS Safari

### ISSUE THREAD

**Issue by SharePointPro** [opentok/opentok-react#105]
I am getting an issue that Iphone users can not publish to my webpage. They are getting the below error:

> VM504 opentok.min.js:31 %cOpenTok:Publisher:error %conStreamAvailableError OT_MEDIA_ERR_ABORTED: Failed to acquire functional stream, this might be caused by the following iOS bug: https://bugs.webkit.org/show_bug.cgi?id=188088

I have looked at the link supplied, but I cant figure out a work around? My code looks like 

 

>             <OTSession
>                     apiKey={config.openTokApi}
>                     sessionId={globalContext.session.response.session.id}
>                     token={globalContext.session.response.session.token}
>                     onConnect={() => {
>                         console.log("OT connected");
> 
>                     }}
>                     onError={(err) => {
>                         console.log("error", err);
>                         window.alert(err.message);
>                         errorLogging.sendLog(JSON.stringify(err));
>                         
>                     }}
>                 >
>                     <OTPublisher properties={{
>                         resolution: '1280x720',
>                         PreferredResolution: '1280x720',
>                         insertMode: 'append',
>                         width: "100%",
>                         height: "100%",
>                         mirror: false,
>                         facingMode: "environment",
>                         fitMode: "contain",
>                         publishAudio: false,
>                         style: { buttonDisplayMode: 'off' },
>                     }}
>                         ref={otPublisher}
>                         onError={(err) => {
>                             console.log("error", err);
>                             errorLogging.sendLog(JSON.stringify(err));
>                         }}
>                     />
>                 </OTSession>

**Comment by SharePointPro** [comment]
Ive found out that setting "Prevent Cross-Site tracking" to disabled on iphone resolves the issue.

however its not a good solution because I cant teach every client to do that.

**Comment by enricop89** [comment]
Is a duplicate of #86 ?
