### ISSUE TITLE
eventHandlers for audioDisabled and audioEnabled

### ISSUE THREAD

**Issue by jaisonka91** [opentok/opentok-react#109]
Can't find event handlers for audio in react version. How can I detect whether subscriber disabled or enabled microphone? #question

**Comment by enricop89** [comment]
@jaisonka91 You can use the `streamPropertyChanged` event on the **Session** object. Example: 

```
this.sessionEventHandlers = {
      streamPropertyChanged: event => {
        console.log('streamPropertyChanged');
      }
    };
```
Documentation: https://tokbox.com/developer/sdks/js/reference/StreamPropertyChangedEvent.html

**Comment by jaisonka91** [comment]
@enricop89 Thanks it worked. Will be great if you can provide this event in OTSubscriber events itself. One more question, how can we close a session properly in react documentation its not there. im not creating a session from react side.
