### ISSUE TITLE
how to select camera if I have multiple camera attached to system

### ISSUE THREAD

**Issue by nbvora** [opentok/opentok-react#122]
How to make device selection while publishing video, is there any provision to chose devices?

Thanks

**Comment by nbvora** [comment]
https://tokbox.com/developer/guides/audio-video/js/#cycleVideo

How to achieve this ?

**Comment by enricop89** [comment]
Hi, you can use the OT.getDevices() function to get a list of mic and camera inputs. From there, you call the initPublisher function using audioSource and videoSource options.

Does it answer your question?

We have sample code in vanillaJs here: https://github.com/opentok/opentok-hardware-setup.js/blob/master/index.html
