### ISSUE TITLE
How to implement RTMP

### ISSUE THREAD

**Issue by nbvora** [opentok/opentok-react#124]
Hi,

I am trying to implement RTMP facebook and youtube, does this library has support for it?
Share snippet if library has support

thanks

**Comment by enricop89** [comment]
https://tokbox.com/developer/rest/#start_broadcast

**Comment by nbvora** [comment]
Thank you for quick support. I was looking for inbuilt library support. Through OTSession or OTPublisher.

**Comment by enricop89** [comment]
@nbvora RTMP setting is on the server-side when you create the session
