### ISSUE TITLE
Voice-only session issue

### ISSUE THREAD

**Issue by yarikpwnzer** [opentok/opentok-react#153]
When publishing voice-only session with latest version 0.11.0, browser still asking me camera permission (Chrome). Here is code:
```react
      <OTPublisher
        session={ session }
        eventHandlers={ this.publisherEventHandlers }
        onError={ this.onPublisherError }
        properties={ {
          publishAudio: enableMic,
          publishVideo: showVideo,
          showControls: false,
          height: '150',
          width: '100%'
        } }
        videoSource={ voipType === Const.chatType.video ? 'camera' : null }
      />
```
Tried videoSource={ null } same result.
From documentation: When you set the videoSource property to null, the publishing client does not request access to the camera, and no video is published.

**Comment by enricop89** [comment]
Hello, which version of @opentok/client are you running? 
I tested `OT.initPublisher('',{videoSource:null})` and it's not asking camera permission. [tested on Chrome 85]

**Comment by yarikpwnzer** [comment]
@enricop89 sorry for late answer, chrome version - 85.
 "opentok-react": "^0.11.0"

I don't have @opentok/client entry in package.json.

**Comment by enricop89** [comment]
You are using the CDN then (https://github.com/opentok/opentok-react#preloadscript-higher-order-component)
Anyway, can you try the following code? 
<OTPublisher
        session={ session }
        eventHandlers={ this.publisherEventHandlers }
        onError={ this.onPublisherError }
        properties={ {
          publishAudio: true,
          publishVideo: false,
          showControls: false,
          height: '150',
          width: '100%'
        } }
        videoSource={ null }
      />

**Comment by yarikpwnzer** [comment]
@enricop89 
```react
<OTPublisher
        session={ session }
        eventHandlers={ this.publisherEventHandlers }
        onError={ this.onPublisherError }
        properties={ {
          publishAudio: true,
          publishVideo: false,
          showControls: false,
          height: '150',
          width: '100%'
        } }
        videoSource={ null }
      />
```
Same, request camera access.

**Comment by yarikpwnzer** [comment]
@enricop89 can you try with preloadScript HOC? I guess bug can be here, since I do not have OT.initPublisher('',{videoSource:null}). Also i'm creating session with createSession Helper.

**Comment by enricop89** [comment]
Sorry forget about OT.Publisher API (it's for the JS SDK).
Anyway, I think it's a typo problem (I fixed my example above as well). You are putting `videoSource` property outside the `properties` object. It should be: 

```
<OTPublisher
        session={ session }
        eventHandlers={ this.publisherEventHandlers }
        onError={ this.onPublisherError }
        properties={ {
          publishAudio: true,
          publishVideo: false,
          showControls: false,
          height: '150',
          width: '100%',
         videoSource={ null }
        } }
/>
```

**Comment by yarikpwnzer** [comment]
@enricop89 haha indeed, thx for help :)
