### ISSUE TITLE
Is this under active development?

### ISSUE THREAD

**Issue by damianesteban** [opentok/opentok-react#156]
Quick question - a few months ago when we were building out a new version of our product we talked with the opentok team and they suggested that we use the opentok-react library. The last commit I see is from July...does the opentok team plan to invest time and resources into this project?

Thank you.

**Comment by enricop89** [comment]
Hi @damianesteban ,  I just wanted to clarify that nothing has changed recently, all of our accelerator sample code and apps are officially community-supported and this has always been the case.

This means it is supported by our user base and also is internal developer relation team on a best effort basis.

**Comment by damianesteban** [comment]
@enricop89 Your React.js SDK is primarily supported by your user base?

**Comment by enricop89** [comment]
As said above, it's supported by our developer relation team on a best effort basis. Pull requests from our user base are welcome and will be reviewed and merged by us.

**Note**: `opentok-react` is **NOT** **officially** supported by Vonage

**Comment by damianesteban** [comment]
@enricop89 Thank you for the clarification. We just forked it - expect some fantastic code incoming. :)
