### ISSUE TITLE
Maintenance Status of this Repository?

### ISSUE THREAD

**Issue by angrytoad** [opentok/opentok-react#159]
My team is currently implementing this library into a video streaming solution for our platform, but I've noticed that there has been little in the way of activity from the first half of 2020, would anybody be able to clarify if this react implementation of the service is still actively receiving support or has focus shifted towards other libraries?

I only ask because we need to consider how we are going to continually support the repository in the long term.

**Comment by enricop89** [comment]
https://github.com/opentok/opentok-react/issues/156
