### ISSUE TITLE
Screen sharing in react hook

### ISSUE THREAD

**Issue by vishnu8429** [opentok/opentok-react#164]
Hi guys,

Can anyone help me to resolve the following issues
1. How to publish an audio while screen share? I tried to enable the audio but its not working in subscribers end.
2. How to remove the chrome popup that's open while screen share starts? or how to handle it from react hook side? Its always comes on top of the window.
3. How to get the publisher mediaStopped event inside window.OT.checkScreenSharingCapability method?

**Comment by enricop89** [comment]
1. the screen sharing is without audio by default. You can use two OTPublisher component, one with the audio/camera feed and the other one with the screen.
2. It's not possible to remove it as it's the standard behaviour of Chrome and other browsers. It's privacy related.
3. `mediaStopped` event is triggered by the OTPublisher component.
