### ISSUE TITLE
session.disconnect(publisher) seems to not be working properly.

### ISSUE THREAD

**Issue by meljason** [opentok/opentok-react#167]
So I have a hangup button with an onClick function appended to it. The function consist of `session.disconnect(publisher)` but when I disconnect the publisher and reconnect again, it shows the subscriber video element twice as if it did not remove the subscriber's element from the session when disconnected. 

I tried using `session.disconnect(subscriber) `but that seems to not work either.

What is the solution for this?

**Comment by enricop89** [comment]
I suspect you  have double event listeners when you republish again. Can you share sample code to reproduce it? 

When you disconnect from a session (session.disconnect()), the client will unpublish and unsubscribe from all the streams in the session, so when you disconnect you shouldn't see any subscriber video element. Can you confirm that?

**Comment by meljason** [comment]
@enricop89 When a subscriber joins the session, the subscriber's video element is appended in the publisher's side. So when I disconnect, the subscriber gets created another time. So the first time I disconnect, subscriber's element is created twice, the second time, it gets created three times and so on. This happens only on the publisher's side though. It seems to be working on the subscriber's side. 

When I disconnect, it does delete all subscriber's video element.

When I investigated, when the publisher disconnect, on the session.on("streamCreated") event, the session.subscribe() is appended. Therefore, it runs twice when its ran.

```
    session.on("streamCreated", function (event) {        
        var subscriberOptions = { 
            insertMode: "append",
            style: { buttonDisplayMode: "off", nameDisplayMode: "on" },
            width: "100%",
            height: "100%"
        }
        subscriber = session.subscribe(event.stream, "subscriber", subscriberOptions,
            err => {
                console.log("Creating the subscriber");

//This console.log is run twice the publisher disconnects and connects again. Which create two subscriber video element. Will create 3 video element if that publisher disconnects and connects a second time.

                if (err) {
                    alert("Publish error " + err.message);
                }
            }    
        );
    });
```

**Comment by enricop89** [comment]
The `streamCreated` event on the **session** object is fired **only when another client starts publishing.** 
The `streamCreated` event on the **publisher** object is fired **when the local client starts publishing.** 

Doc: https://tokbox.com/developer/sdks/js/reference/StreamEvent.html

Anyway, are you using the `opentok-react` library on your code? 

From the snippet above it seems like you are using Vanilla JS. Or, if you are using that code in the opentok-react library with also an OTSubscriber object in the render function, it could be that you are subscribing twice to the same stream.  The OTSubscriber object handles the subscribe process itself (https://github.com/opentok/opentok-react/blob/master/src/OTSubscriber.js#L67), there is no need to call `.subscribe`.

**Comment by meljason** [comment]
I am actually using vanilla javascript alongside with React. But all my functions for the integration of Vonage are made in vanilla javascript. So I am not using the opentok-react.

When I console log into the session.on("streamCreated") function, after the local client disconnects and reconnects again, it console logs twice and if the local client disconnects a second time and reconnects again, it console log 3 times. So I do not think it is because of a function running twice. 

I just feel like my disconnect function is not working properly. So here is a snippet of my disconnect code.

```
export function stopStreaming() {
    session && session.disconnect(publisher);
}
```

Could it be that this function is not disconnecting the other client? Am I doing something wrong here?

**Comment by meljason** [comment]
@enricop89 could you help me with that please?

**Comment by enricop89** [comment]
```
export function stopStreaming() {
    session && session.disconnect(publisher);
}
```

This function only disconnected the publisher (the local video basically). You can make sure that the publisher has been disconnected by checking publisher.on('streamDestroyed'). 

https://tokbox.com/developer/sdks/js/reference/Session.html#disconnect

**Comment by meljason** [comment]
@enricop89 Thanks! I added this and I can see that it says that the stream ended, however, I see that the camera stills runs based by the camera icon on google chromes tabs and my webcam's camera stays on. Do I need to do additional stuff to completely disconnect the call?

**Comment by enricop89** [comment]
`Calling the disconnect() method ends your connection with the session. In the course of terminating your connection, it also ceases publishing any stream(s) you were publishing.`

When you call disconnect, the publisher is destroyed as well. It seems like that you are either calling getUserMedia somewhere in your code or you have additional active publishers. It's difficult to say without seeing the code.

**Comment by meljason** [comment]
@enricop89 I indeed used OT.getUserMedia. How are we supposed to disconnect the session when I used getUserMedia?

**Comment by enricop89** [comment]
Please check: https://github.com/opentok/opentok-react/issues/143#issuecomment-816502976

**Comment by meljason** [comment]
@enricop89 Thank you. This solved my issue to disconnect the getUserMedia. However, I still have another issue. In my webapp, I am trying to display the camera preview first where afterwards I would click a button that would initiate the video conference. 

In order for me to do the preview, I did an initPublisher on a dom element "preview".

```

publisher = OT.initPublisher(
	'preview',
	{
		insertMode: 'append',
		style: { buttonDisplayMode: 'off', nameDisplayMode: 'on' },
		width: '100%',
		height: '100%',
	}
);
```

Then when I click on the button, there would be a click event listener which by then would run another initPublisher but on subscriber

``` 
publisher = OT.initPublisher(
	'subscriber',
	{
		insertMode: 'append',
		style: { buttonDisplayMode: 'off', nameDisplayMode: 'on' },
		width: '100%',
		height: '100%',
	}
);

I would then use JS to hide the preview container. However, this does not actually stop the initialization of the preview.

What would be the best way to disconnect the preview initialized at the beginning?

**Comment by meljason** [comment]
@enricop89 After couple of testing, I realized that when I have to instances of OT.initPublisher then I use the session.disconnect(publisher) function, it disconnects only one of the OT.initPublisher. How do I disconnect all of the instances of OT.initPublisher?
