### ISSUE TITLE
Basic Usage Leads to Errors

### ISSUE THREAD

**Issue by tubbo** [opentok/opentok-react#169]
Basic usage of this library leads to a ton of errors:

```
Warning: Failed prop type: Invalid prop `children` supplied to `OTSession`.

OpenTok:Publisher:error onStreamAvailableError OT_CONSTRAINTS_NOT_SATISFIED: It's not possible to satisfy one or more constraints passed into the getUserMedia function (getUserMedia error: OverconstrainedError) +0ms

OpenTok:GlobalExceptionHandler:error OT.exception :: title: Unable to Publish (1500) msg: GetUserMedia +0ms

OpenTok:Session:error 1500 +0ms Session.publish :: It's not possible to satisfy one or more constraints passed into the getUserMedia function (getUserMedia error: OverconstrainedError)
```

I'm just doing something real simple, following https://learn.vonage.com/blog/2019/07/16/opentok-react-components-dr/

`getUserMedia` works with normal usage so I'm not sure why OT is having so many problems.

**Comment by davibarberini** [comment]
I'm getting the same error, but only when using Firefox, did you find a solution @tubbo ?

**Comment by tubbo** [comment]
@davibarberini it's been a while since this happened but not that I can recall.
