### ISSUE TITLE
Is there a way to switch speakers just like setAudioSource and setVideoSource?

### ISSUE THREAD

**Issue by meljason** [opentok/opentok-react#171]
I was just wondering if there was a way to change speakers based on the ids of the speakers. Currently I managed to fetch the list of speakers in an option select tag using enumerateDevices from navigator when filterred the speakers with the "kind" audiooutput. Is there a way to switch speakers on opentok?

**Comment by enricop89** [comment]
The only way is to use [setSinkId](https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/setSinkId) but bare in mind that is an experimental feature (check browsers support)
