### ISSUE TITLE
Is there a way to stop screenshare in OpenTok?

### ISSUE THREAD

**Issue by meljason** [opentok/opentok-react#172]
Hi, I would like to know if you guys had a feature that completely stops screensharing?

Currently I am using the OT.checkScreenSharinCapability and initializing a publisher on the screen preview div. This is the reference:
https://tokbox.com/developer/guides/screen-sharing/js/

But I do not seem to find a method which would stop the screen share. What I did was removing the video tag using a JS function `remove()` but on Google Chrome it would show the "xxx stop sharing your screen" bar. Is there a way to completely remove it?

**Comment by enricop89** [comment]
you call `.destroy()` on the publisher object or just unpublish the stream using `session.unpublish(screenshare)`
