### ISSUE TITLE
How do I detect if a user pressed "Cancel" or on the Close button on the Sharing Screen promted by "OT.checkScreenSharingCapability" ?"

### ISSUE THREAD

**Issue by meljason** [opentok/opentok-react#179]
I added the sharing screen function by using OT.checkScreenSharingCapability, then published a video source screen. However, before sharing the screen, it would prompt the user asking which screen I want to share. Is there an event to know whether the user pressed close or the cancel button?

**Comment by enricop89** [comment]
publisher.on(`accessDenied`) should work

**Comment by rohanrana** [comment]
On-screen share, popup cancel am getting this error 
**_Unhandled Rejection (OT_USER_MEDIA_ACCESS_DENIED): End-user denied permission to hardware devices (getUserMedia error: NotAllowedError)_**


please help me out @enricop89

**Comment by meljason** [comment]
> publisher.on(`accessDenied`) should work

Thank you! It works.
