### ISSUE TITLE
Styling and lifecycle capabilities

### ISSUE THREAD

**Issue by mbouxin** [opentok/opentok-react#29]
To improve the styling it would be a great addition to be able to change the dimensions of the video containers with props.

Additionnaly, the stream created could be provided when calling the onPublish and onSuscribe.

**Comment by msach22** [comment]
@mbouxin You can use the `OTPublisherContainer` and the `OTSubscriberContainer` classes to style to publisher and subscribers.

**Comment by enricop89** [comment]
IT should be resolved now with `0.10.0`
