### ISSUE TITLE
Unable to set `publishVideo` to false

### ISSUE THREAD

**Issue by eladmoshe** [opentok/opentok-react#36]
When I set on a `OTPublisher` `publishVideo` property to `false`, I get the following error message:
```
opentok.js:19601 Video element paused, auto-resuming. If you intended to do this, use publishVideo(false) or subscribeToVideo(false) instead.
(anonymous) @ opentok.js:19601
_playVideoOnPause @ opentok.js:24789
```
And the subscriber continue to receive the video stream.

`opentok-react`:0.7, `@opentok/client` :2.14.7

**Comment by nlyn** [comment]
I'm also experiencing this issue.

**Comment by Hoffmano** [comment]
@eladmoshe what do you do to solve the problem?
