### ISSUE TITLE
getting errors on end call

### ISSUE THREAD

**Issue by mohitgarg** [opentok/opentok-react#37]
```
import React, { Component } from 'react';
import { OTSession, OTStreams, preloadScript, OTPublisher, OTSubscriber } from 'opentok-react';
import { chrApi } from '../../api/api';

class SCOpenTok extends Component {
  state = {
    error: null,
    connected: false,
    apiKey: '',
    sessionId: '',
    token: '',
  };

  async componentDidMount() {
    const obj = await chrApi('post', 'callpatient', { patientId: this.props.match.params.id });
    this.setState({
      apiKey: obj.data.apiKey,
      sessionId: obj.data.sessionId,
      token: obj.data.token,
    });
  }

  sessionEvents = {
    sessionConnected: () => {
      this.setState({ connected: true });
    },
    sessionDisconnected: () => {
      this.setState({ connected: false });
    },
  };
  onError = err => {
    this.setState({ error: `Failed to connect: ${err.message}` });
  };

  render() {
    return (
      <div className={'opentok'}>
        {this.state.apiKey ? (
          <OTSession
            apiKey={this.state.apiKey}
            sessionId={this.state.sessionId}
            token={this.state.token}
            eventHandlers={this.sessionEvents}
            onError={this.onError}
            onConnect={e => console.log(e, 'Connected Succesfully')}
            ref={instance => {
              this.otSession = instance;
            }}
            className={'opentok'}
          >
            <OTPublisher />
            <OTStreams>
              <OTSubscriber />
            </OTStreams>
          </OTSession>
        ) : (
          ''
        )}
        <button onClick={() => this.otSession.sessionHelper.disconnect(this.state.sessionId)}>
          {' '}
          End call
        </button>
      </div>
    );
  }
}

SCOpenTok.propTypes = {};
SCOpenTok.defaultProps = {};

export default preloadScript(SCOpenTok);
```

**This is the route defined**

```
<Route
          path={'/patient/:id/video'}
          exact
          component={cProps => (
            <SCOpenTok
              loadingDelegate={<div>Loading...</div>}
              opentokClientUrl="https://static.opentok.com/v2/js/opentok.min.js"
              {...cProps}
            />
          )}
        />

```

`Uncaught TypeError: Cannot read property 'off' of null
    at OTSession.destroySession (OTSession.js?57c4:93)
    at OTSession.componentWillUnmount (OTSession.js?57c4:60)
    at callComponentWillUnmountWithTimer (react-dom.development.js?61bb:9703)
    at HTMLUnknownElement.callCallback (react-dom.development.js?61bb:100)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?61bb:138)
    at invokeGuardedCallback (react-dom.development.js?61bb:187)
    at safelyCallComponentWillUnmount (react-dom.development.js?61bb:9710)
    at commitUnmount (react-dom.development.js?61bb:9956)
    at commitNestedUnmounts (react-dom.development.js?61bb:9992)
    at unmountHostComponents (react-dom.development.js?61bb:10279)`

When ever I click on the end call and go back home or to any other route this error is popping up

**Comment by mohitgarg** [comment]
Never mind. It's resolved. Turned out there was an issue with Error handlers in my code. Thanks for the awesome library.

**Comment by xporium** [comment]
Hi,
can you tell me how to do an end called? because I used the same above code but it's not running and where to initiate or defined this.otSession?
 can you use SessionHelper?

Because I want the same end the call by the publisher when clicking on the "END Call" button.

Thanks

**Comment by inlightmedia** [comment]
`this.otSession` is a ReactJS ref. 

See: https://reactjs.org/docs/refs-and-the-dom.html

This ref takes the OTSession DOM element and exposes the sessionHelper object to allow you to end the call with the included disconnect method: `this.otSession.sessionHelper.disconnect();`

Make sure you are implementing the react ref properly using the latest react docs as shared above.

**Comment by xporium** [comment]
Hi,
thanks for a reply now I m getting the same error which you mentioned before "Uncaught TypeError: Cannot read property 'off' of null at OTSession.destroySession". So how you resolved this problem I'm getting the same error means after disconnect the session and popup would close then cant render parent page just because of getting error.

Thanks

**Comment by mohitgarg** [comment]
@xporium It doesn't happen for me when I don't any `eventHandlers` props I couldn't figure out why. Any idea @inlightmedia  ?

**Comment by inlightmedia** [comment]
One reason that would cause this error is if the object you are listening to is already destroyed when you call session.off() or publisher.off("eventName", eventHandler) etc. If you use a conditional `if (session) { session.off("eventName", eventHandler) }` this could be prevented. Hope that helps.

**Comment by enricop89** [comment]
@xporium @mohitgarg @inlightmedia thanks for the support guys.

I am trying to reproduce the issue using `opentok-react:0.10.0` and `@opentok/client": "^2.17.0`.

This is the code

```
export default class App extends React.Component {
	constructor(props) {
		super(props);
		this.otSession = React.createRef();
                this.sessionEventHandlers = {
			sessionConnected: () => {
				this.setState({ connection: 'Connected' });
			},
			sessionDisconnected: () => {
				this.setState({ connection: 'Disconnected' });
			},
			sessionReconnected: () => {
				this.setState({ connection: 'Reconnected' });
			},
			sessionReconnecting: () => {
				this.setState({ connection: 'Reconnecting' });
			},
		};
        }
       
       disconnectSession = () => {
		this.otSession.current.sessionHelper.disconnect()
	}

	render() {
		const { apiKey, sessionId, token } = this.props.credentials;
		const { error } = this.state;
		return (
			<div>
				<button onClick={this.disconnectSession}>Disconnect</button>
				{error ? (
					<div className="error">
						<strong>Error:</strong> {error}
					</div>
				) : null}
				<OTSession
					apiKey={apiKey}
					sessionId={sessionId}
					token={token}
					ref={this.otSession}
					onError={this.onSessionError}
					eventHandlers={this.sessionEventHandlers}
				>
					<OTPublisher
						properties={{ publishVideo, width: 200, height: 200 }}
						onPublish={this.onPublish}
						onError={this.onPublishError}
						eventHandlers={this.publisherEventHandlers}
					/>
					<OTStreams>
						<OTSubscriber
						  properties={{ width: 200, height: 200 }}
				                  onSubscribe={this.onSubscribe}
						  onError={this.onSubscribeError}
						  eventHandlers={this.subscriberEventHandlers}
						/>
					</OTStreams>
				</OTSession>
			</div >
		);
	}
}
```

**Comment by mohitgarg** [comment]
Hi @enricop89 , you are right. The code that you posted works but if you are redirecting the user after that event that's when it happens. Like the code I posted in my first comment

**Comment by mohitgarg** [comment]
@inlightmedia Thanks for the response but I don't understand how wrapping the entire logic with this condition might help, because if you passing the event handler it would still throw the same error

`if (this.otSession.sessionHelper.session) { /* End Session Logic */}`

If you are passing the entire `eventHandlers` prop to the `this.sessionHelper.session.off` method what exactly is the method it is expecting to be inside the `eventhandlers` prop. That is still unclear to me.

**Comment by alisrour37** [comment]
@mohitgarg 
> Never mind. It's resolved. Turned out there was an issue with Error handlers in my code. Thanks for the awesome library.

How did you solve it?

**Comment by dineshpanjwani33** [comment]
Getting same issue. @mohitgarg how did you solved it?
