### ISSUE TITLE
video issue in iOS Safari 11

### ISSUE THREAD

**Issue by sa-js** [opentok/opentok-react#39]
I am getting this exception in Safari 11 iOS in video. This is due to some recent changes in autoplay policy by Safari. 
Error is : Unhandled Rejection (NotAllowedError): The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.

How to solve this? For Safari docs suggested video to be H.264, but it also doesn't work either. How to override the default behaviour of Safari 11?

I saw an example in their official docs : https://github.com/opentok/opentok-web-samples/tree/master/React-Basic-Video-Chat. This works finely in Safari 11 when I checked it's live preview. I have used the same code in my React based application but it only works when I enable Autoplay for this website in Safari 11. Otherwise it breaks with an exception which I showed above with said error.

@aiham any thoughts on this from your side?
@aullman 
@opentok
@msach22

**Comment by sa-js** [comment]
It works. I think I had some issue with my code. Closing.

**Comment by StanislavMckDev** [comment]
Had exactly this problem. Fixed by import '@opentok/client' in root index.js.
