### ISSUE TITLE
Error running the example app

### ISSUE THREAD

**Issue by MiguelArmendariz** [opentok/opentok-react#41]
Greetings I tried today to run the app, I followed the instructions but I get the next error:

"python" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opentok-react@0.7.0 example: `cd example && browserify -o bundle.js app.js && python -m SimpleHTTPServer`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opentok-react@0.7.0 example script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

It says python is not recognized as a command

**Comment by sa-js** [comment]
It will run on Node JS...Follow steps exactly then you will have no issue...

**Comment by msach22** [comment]
@MiguelArmendariz Could you please verify that you ran `yarn` in the root directory?

**Comment by MiguelArmendariz** [comment]
I think  I did it.  I don't remember  because after a while trying I made my project work

**Comment by msach22** [comment]
Sounds good @MiguelArmendariz!

I'm going to close this issue because I can't reproduce it. Please re-open if this still persists.

**Comment by MiguelArmendariz** [comment]
Steps done: 

git clone "repoURL";
cd opentok-react/example
cp config.template.js config.
cd ..
npm install (Here i got a few warnings and a suggestion to run npm audit to fix vulnerabilities).
npm run example

result: 

```
cd example && browserify -o bundle.js app.js && python -m SimpleHTTPServer

"python" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! opentok-react@0.8.0 example: `cd example && browserify -o bundle.js app                                                                                                                .js && python -m SimpleHTTPServer`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the opentok-react@0.8.0 example script.
npm ERR! This is probably not a problem with npm. There is likely additional log                                                                                                                ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Miguel\AppData\Roaming\npm-cache\_logs\2018-10-31T18_55_28                                                                                                                _799Z-debug.log
```
