### ISSUE TITLE
Controls not working on the Opentok Video 

### ISSUE THREAD

**Issue by sa-js** [opentok/opentok-react#42]
I am working on the video in Opentok. I added controls like publishAudio and publishVideo in my React app. I have changed the layout of video of publisher and subscriber a bit to beautify the UI. I have set the publishVideo in the beginning to true and I am toggling it's status with a function but issue is that function works and state of publishVideo also toggles correctly but video does not hide. Also I want to remove the mic control which is shown by default at the publisher and subscriber video. Any thoughts
from your side @msach22 ?

**Comment by MiguelArmendariz** [comment]
Greetings sa-js 
Let me understand what are you trying to do. You want to create a custom control bar for subscribers?
something like this?:

![image](https://user-images.githubusercontent.com/29263369/46089875-15731c80-c175-11e8-9c39-969ab8334bdb.png)

**Comment by sa-js** [comment]
@MiguelArmendariz Yeah. Exactly. I have added buttons but the controls are not working like I have added publishAudio and publishVideo in my component state in beginning to true. Now I want to toggle the state of both Audio and Video to mute/unmute and hide/show respectively. But issue is that both are toggled correctly but they don't affect the status of video.

**Comment by MiguelArmendariz** [comment]
Well I'm going to assume you have set this controls inside a subscriber component. 
Inside the subscriber component my state is:

this.state = {
    audio:true,
    video:true
}

And have a function for the audio: (outside constructor)
muteUnmute = () => {
      this.setState(prevState => ({
               audio: !prevState.audio
        }));
}

So when the button is clicked it calls that function and set the audio to false
(the same works for video).

if you have a similar code but it's not working. can I see it to help you?

**Comment by sa-js** [comment]
@MiguelArmendariz I have checked your code too but it's not working as expected.

**Comment by sa-js** [comment]
@MiguelArmendariz you can see the code below:

class OpenTok extends Component {
constructor(props) {
super(props);
this.state = {
   audio : true,
   video : true,
}
}

toggleVideo = () => {
    console.log('RunVideo')
    this.setState(prevState => ({
    video: !prevState.video
    }));
    }

  toggleAudio = () => {
    this.setState(prevState => ({
    audio: !prevState.audio
    }));
    }

render() {
return (
<OTSession
          apiKey={API_KEY}
          sessionId={this.props.users.videoData.session}
          token={token}
          onError={this.onSessionError}
          eventHandlers={this.sessionEventHandlers}
          ref={instance => (this.otSession = instance)}
        >
            <div className="opentok-footer">
        <div className="video-icons" onClick={this.endCall}><FontAwesomeIcon icon={faTimes} size="3x"/>
        <div>Leave</div>
          </div>
          <div className="video-icons" id="video-button" onClick={this.toggleVideo}>
          <FontAwesomeIcon icon={faCamera} size="3x"/>
        <div> {video ? 'Disable' : 'Enable'} Video</div>
        </div>
        <div className="video-icons" onClick={this.toggleAudio}>
          <FontAwesomeIcon icon={faMicrophone} size="3x"/>
        <div>Mic {audio ? 'Off' : 'On'}</div>
        </div>
        </div>
       
          <OTPublisher
            onPublish={this.onPublish}
            onError={this.onPublishError}
            eventHandlers={this.publisherEventHandlers}
          />
          <OTStreams >
            <OTSubscriber
              onSubscribe={this.onSubscribe}
              onError={this.onSubscribeError}
              eventHandlers={this.subscriberEventHandlers}
            />
          </OTStreams>
        </OTSession>
)

**Comment by MiguelArmendariz** [comment]
Okay, I'm using session helper instead of OTSession. I don't know if you have components for Publisher and  Subscriber where OTpublisher and OTsubscriber are respectively.

For subscriber streams:

```
export default class Subscriber extends Component {
    constructor(props) {
        super(props);

        this.state = {
            error: null,    
            audio: true,    // This is to listen or not to the streamer.
            video: true,    // this is to hide or display the streamer video.
        }
    }
// Mute or unmute selected stream
    toggleAudio = () => {        
        this.setState(prevState => ({
            audio: !prevState.audio
        }));
    }

// hide or display video of selected stream
    toggleVideo = () => {       
        this.setState(prevState => ({
            video: !prevState.video
        }));
    }

render() {
        if(this.state.error) {
            return(
                <div>{this.state.error}</div>
            );
        }
        else {
            return(
                <OTSubscriber
                    session={this.props.session}
                    stream={this.props.stream}
                    properties={{
                        subscribeToAudio: this.state.audio,  // set the state of the audio of the stream
                        subscribeToVideo: this.state.video,  // set the state of the video of the stream
                        showControls: false,                 // Hide provided controls to make custom control bar
                    }}

                    onError={this.onError}
                />
            );
        }
    }
}
```

and For the publisher: 

```
export default class Publisher extends Component {
    constructor(props) {
        super(props);

        this.state = {
            error: null,
            audio: false,           // set the user audio to mute at the start
            video: true,            // set the video of the user to show
            videoSource: 'camera'             
        };
    }

// mute/unmute audio
    toggleAudio = () => {
        this.setState(prevState => ({
            audio: !prevState.audio
        }));
    }

    // display/hide video
    toggleVideo = () => {
        this.setState(prevState => ({
            video: !prevState.video
        }));
    }

render() {
    return(
       <div>
            <OTPublisher
                        session={this.props.session}
                        properties={{
                            publishAudio: this.state.audio,
                            publishVideo: this.state.video,
                            showControls: false,
                            videoSource: this.state.videoSource === 'screen' ? 'screen' : undefined,
                            name: this.props.UserName,  //this display a name seen in subscribers
                        }}
                        onError={this.onError}
                    /> 
       </div>
    )
}

```

**Comment by sa-js** [comment]
@MiguelArmendariz I got it but as they have done in their React Example App they are importing all OTPublisher and OTSubscriber from opentok-react package. If I do your way, how will I use Publisher and Subscriber components?
Currently I have this:
<OTSession
          apiKey={API_KEY}
          sessionId={this.props.users.videoData.session}
          token={token}
          onError={this.onSessionError}
          eventHandlers={this.sessionEventHandlers}
          ref={instance => (this.otSession = instance)}
        >    
         {/* <button onClick={this.endCall}>End Call</button>  */}
            <div className="opentok-footer">
        <div className="video-icons" onClick={this.endCall}><FontAwesomeIcon icon={faTimes} size="3x"/>
        <div>Leave</div>
          </div>
          <div className="video-icons" id="video-button" onClick={this.toggleVideo}>
          <FontAwesomeIcon icon={faCamera} size="3x"/>
        <div> {video ? 'Disable' : 'Enable'} Video</div>
        </div>
        <div className="video-icons" onClick={this.toggleAudio}>
          <FontAwesomeIcon icon={faMicrophone} size="3x"/>
        <div>Mic {audio ? 'Off' : 'On'}</div>
        </div>
        </div>
       
          <OTPublisher
            onPublish={this.onPublish}
            onError={this.onPublishError}
            eventHandlers={this.publisherEventHandlers}
          />
          <OTStreams >
            <OTSubscriber
              onSubscribe={this.onSubscribe}
              onError={this.onSubscribeError}
              eventHandlers={this.subscriberEventHandlers}
            />
          </OTStreams>
        </OTSession>

**Comment by MiguelArmendariz** [comment]
Sorry I haven't check this for a while, Currently I'm using `SessionHelper.disconnect();` because It's just a module of the whole app right now. And It enter like in a void status haha because you now cant see anything but the publisher controls.  

What's the error you got?

**Comment by msach22** [comment]
Apologies for the delay here. Are you still facing this issue?

**Comment by sa-js** [comment]
No fixed
