### ISSUE TITLE
Error from latest @opentok/client library

### ISSUE THREAD

**Issue by eladmoshe** [opentok/opentok-react#46]
The latest library complains about passing class names. It receives from `opentok-react` the class names `"OT_root OT_subscriber"` and prints an error:
`logging.warn('passing classNames to widgetView is deprecated');`

![image](https://user-images.githubusercontent.com/1702227/47966267-535b3e80-e059-11e8-9f40-7e826f6df4e4.png)

I am using
```
"@opentok/client": "2.15.3",
"opentok-react": "0.8.0"
```

**Comment by blephy** [comment]
Hi,

Same issue here.

Happening in `WidgetView line 123` created by `OTPublisher`

**Comment by msach22** [comment]
This will be patched with the next release of `@opentok/client`. I'll update the issue when the release goes out!

**Comment by msach22** [comment]
This fix for this warning has been released with 2.15.9. Please let me know if you have any questions!
