### ISSUE TITLE
Document getSubscriber

### ISSUE THREAD

**Issue by wyqydsyq** [opentok/opentok-react#49]
It mentions in the README that in order to manipulate the instance of OT.Publisher you need to use the `getPublisher` method of the `OTPublisher` component.

There is currently no documentation on this method, and the only example is in a test where it is being used to access the component instance via Enzyme. This is not how components are used in the real world, there needs to be documentation on usage of the method or an example of using it in an app.

**Comment by aiham** [comment]
From https://github.com/opentok/opentok-react#otpublisher-component

> To facilitate this the Publisher instance is exposed via the getPublisher() component method. You should always call this method to get the latest Publisher instance instead of keeping a reference to it as it's possible for the Publisher instance to change, leaving you with a stale reference.

and

> There are plans to support more Publisher properties but for now you will have to call getPublisher() to retrieve the Publisher instance and make the necessary changes yourself.

It's not ideal but this was low priority when first implemented. Feel free to submit a PR if you'd like this improved.

**Comment by wyqydsyq** [comment]
Yes that tells you to use the `getPublisher` method of `OTPublisher` component instance in order to change the OT.Publisher instance, what I am saying is there is no documentation or examples on how `getPublisher` is actually supposed to be used.

How am I supposed to call `getPublisher` from the `OTPublisher` instance? Neither of the below works:
```jsx
  render(){
    const p = <OTPublisher {....props} />;
    console.log(p.getPublisher());
  }
```
-> `getPublisher is not a function`

```jsx
  render(){
    const p = new OTPublisher(...props);
    console.log(p.getPublisher());
  }
```
-> `getPublisher is not a function`


I'm happy to submit a PR to add documentation on how it is intended to be used, but first I need to understand that myself.

**Comment by wyqydsyq** [comment]
The above does not work. It results in `this.ref` having a value of
```ts
 {current: OTPublisher}
```
Which does not have a `.getPublisher()` method.

**Comment by aiham** [comment]
So then use `current`: `this.otPublisher.current.getPublisher()`

You can figure this out on your own but looking up the documentation for (React.createRef)[https://reactjs.org/docs/refs-and-the-dom.html]

**Comment by wyqydsyq** [comment]
`this.otPublisher.current` appears to be an actual instance of `OTPublisher` and also lacks a `getPublisher` method, I have no idea whether the `current` property will be dynamically returning a live reference of the current `OTPublisher` or just the initial one I already have a reference of

![image](https://user-images.githubusercontent.com/621277/51507971-1ecc7700-1e3f-11e9-8572-1b4d9594cf53.png)

**Comment by elbecita** [comment]
I was facing a similar issue, but with the subscriber. In order to have access to the object that `getSubscriber` returns I had to wait for `componentDidMount` but also wait for the next animation frame.

So having this:
```
componentDidMount() {
    requestAnimationFrame(() => {
      console.log('>>>>> 2: ', this.otSubscriber.current.getSubscriber());
    });
    
    console.log('>>>>> 1: ', this.otSubscriber.current.getSubscriber())
  }
```
1 prints null, but 2 prints the subscriber object. This makes sense, according to React lifecycle and how `componentDidMount` works. So make sure you're not accessing your refs object too early.

**Comment by wyqydsyq** [comment]
@ashifa454 the suggestion made by @aiham ended up working for me, just had to use `.current` as mentioned above. I'll try to get around to submitting a PR to add this to the docs

**Comment by enricop89** [comment]
I think you can also do something like this: 

```javascript
class MyComponent extends React.Component {
  constructor(props) {
    super(props);
    this.otPublisher = React.createRef();
  }
  getPublisherStats(){
    this.otPublisher.getPublisher().getStats((err, stats) => console.log(err, stats));
  }
  render() {
    return <OTPublisher ref={(instance) => { this.otPublisher = instance }} />;
  }
}
```

Using the instance inside the ref function (`ref={(instance) => { this.otPublisher = instance }}`), you access the `OTPublisher`directly.

**Comment by msach22** [comment]
We've gone ahead and documented this. Closing the issue!
