### ISSUE TITLE
OT is not defined React.js

### ISSUE THREAD

**Issue by saadpasta** [opentok/opentok-react#56]
I am trying to use OT.checkSystemRequirements() but when I am using it's giving an error OT is not defined I have installed the library and added script file can someone tell me how to get OT.

**Comment by msach22** [comment]
@saadpasta Have you installed the OpenTok JS SDK. You can add it using the `@opentok/client` package on NPM or the JS SDK link here:
` <script src="https://static.opentok.com/v2/js/opentok.min.js"></script>`

**Comment by brianbodollo** [comment]
Wrap your component with `preloadScript`.

```javascript
import {preloadScript} from 'opentok-react'

function SomeComponent {
  // do your thing
}

export default preloadScript(Component)
```

**Comment by msach22** [comment]
Thanks for helping @brianbodollo. 

I'm going to go ahead and close this issue.

**Comment by thejoud1997** [comment]
> Wrap your component with `preloadScript`.
> 
> ```js
> import {preloadScript} from 'opentok-react'
> 
> function SomeComponent {
>   // do your thing
> }
> 
> export default preloadScript(SomeComponent)
> ```

thank you so much my friend, this fixed my issue
