### ISSUE TITLE
Add documentation on how to style the publishers and subscribers

### ISSUE THREAD

**Issue by msach22** [opentok/opentok-react#57]
When creating the publishers and subscribers, the library assigns the `OTPublisherContainer` and `OTSubscriberContainer` classes to their respective DOM elements.

**Comment by michaellopez** [comment]
@msach22 
One problem is that `OTPublisher` and `OTSubscriber` have an anonymous `div` that can't be directly targeted with styling. See https://github.com/opentok/opentok-react/blob/master/src/OTPublisher.js#L173 and https://github.com/opentok/opentok-react/blob/master/src/OTSubscriber.js#L109
This makes it harder to use `properties` to set `width:100%,height:100%` on both `OTPublisher` and `OTSubscriber`. I'll send a PR...

**Comment by coletivo** [comment]
Whats the status on this ^? I am running into the same issues

**Comment by msach22** [comment]
This is now solved with #59. Please use v0.10
