### ISSUE TITLE
when updating component TokBoxVideo with new sessionId+token - it won't create stream

### ISSUE THREAD

**Issue by nitzanma** [opentok/opentok-react#62]
I have a case where I trigger Update (not mount) for TokBoxVideo Component with new sessionId and new token - but no stream is created, hence i won't see any video.

meanwhile I solved it by adding a key prop to the component, equals to the sessionId - which forces re-mount, and solves the issue.

**Comment by msach22** [comment]
@nitzanma Thanks for filing this issue. We recommend creating a new instance of the `OTSession` component when you want to change credentials i.e unmounting and remounting the component.

**Comment by msach22** [comment]
@nitzanma I'm going to go ahead and close this issue. Please use the recommendation above.
