### ISSUE TITLE
Screen Sharing

### ISSUE THREAD

**Issue by sarifconrati** [opentok/opentok-react#66]
Is there anyway to implement screen sharing feature with opentok-react library.

**Comment by msach22** [comment]
@sarifconrati Yes, you can share your screen by using the `properties` prop and setting the `videoSource` property to `screen` like so:

```
const MyComponent = () => {
 return (
       <div>
        <OTSession ...>
        <OTPublisher properties={{ videoSource: 'screen' }}
        </OTSession>
      </div>
 );
}
```

**Comment by Itzli2000** [comment]
When I share screen, the audio stops.

How can I keep sharing audio from the same source and share the screen?
