### ISSUE TITLE
Support for passing in options when initializing a session

### ISSUE THREAD

**Issue by mdillavou** [opentok/opentok-react#75]
The initSession has the ability to pass in a keyword list of options [1]. However, the opentok-react doesn't expose this parameter. This is necessary for any customers using enterprise features, like ip whitelisting.

I have put up a pull request: #74 to add in support for this.

[1] https://tokbox.com/developer/sdks/js/reference/OT.html#initSession

**Comment by enricop89** [comment]
Supported in `0.10.0`
