### ISSUE TITLE
videoDisabled on Subscriber eventHandlers doesn't work any more

### ISSUE THREAD

**Issue by castroCrea** [opentok/opentok-react#76]
**videoDisabled** work perfectly before but since couple of week it is not trigger when 
publishVideo in OTPublisher is toggle from true to false.
Despite the event videoEnabled is trigger when it's toggle to false or true, with the type videoEnabled in both case.

I found out that videoDisabled is trigger each time we toggle publishVideo and with OTPublisher init value publishVideo=false and return event type videoDisabled

And videoEnabled is trigger each time we toggle publishVideo and with OTPublisher init value publishVideo=true  and return event type videoEnabled

Do you have any clue? The problem it's certainly on openTok side but i don't know where to ask them.

```
          <OTSubscriber
          key={stream.id}
          stream={stream}
          session={session}
          eventHandlers={{
            videoElementCreated: this.initSubscriber,
            audioLevelUpdated: speakerDetection,
            videoDisabled: () => console.log('disabled'),
            videoEnabled: () => console.log('enabled'),
          }} 
/>
```

thank alot

**Comment by msach22** [comment]
@castroCrea Are you still seeing this error? If so, could you please share which version of the JS SDK you're using?
