### ISSUE TITLE
How to call disconnect method

### ISSUE THREAD

**Issue by sadashivm** [opentok/opentok-react#78]
Hello,

`<OTSession
          apiKey={tokboxConfig.apiKey}
          sessionId={tokboxConfig.sessionID}
          token={tokboxConfig.token}
          onError={onError}
        >
          <OTStreams>
            <TokBoxSubscriber />
          </OTStreams>
        </OTSession>`

How to call disconnect method, once I leave the component.
Because i'm not creating any OT session object. I'm using your plugin.
How to know stream video is connected or not. For example I want to show some message if subscriber is not connected.

**Comment by enricop89** [comment]
https://github.com/opentok/opentok-react/issues/94#issuecomment-595752253
