### ISSUE TITLE
Can't hear audio when user share screen

### ISSUE THREAD

**Issue by Itzli2000** [opentok/opentok-react#84]
When user toggle between camera and screen share, the audio remains off, but when user return to camera the audio can be switched (on/off).
I need to send audio as well as the screen share

`<OTPublisher
          properties={{
            publishAudio: this.state.audio,
            publishVideo: this.state.video,
            videoSource: this.state.screen,
            showControls: true
          }}
          onError={this.onError}
        />
        <OTStreams>
          <OTSubscriber
            properties={{
              subscribeToAudio: this.state.suscribeAudio
            }}
          />
        </OTStreams>`

In the audio publisher I send 'true' as parameter.

**Comment by Itzli2000** [comment]
The same thing happen when I send screen share as default parameter instead of camera share

**Comment by johnnyrainbow** [comment]
Same issue, is there any way around this?

**Comment by enricop89** [comment]
When you set `videoSource: screen`, the SDK will ignore any audio option. Anyway, if you want to send audio while screen-sharing you have two  options: 

1.  publish two streams: one with audio/video and one with screen
2. use `videoSource: screen` and set audioSource to a MediaTrack.

For 2):

```
const publish = Promise.all([
  OT.getUserMedia({
    videoSource: 'screen'
  }),
  OT.getUserMedia({
    videoSource: null
  })
])
.then(([screenStream, micStream]) => {
  return OT.initPublisher(null, {
    videoSource: screenStream.getVideoTracks()[0],
    audioSource: micStream.getAudioTracks()[0]
  });
});
```

**Comment by CarlosTrapet** [comment]
Be mindful of using option number 1 though, as there's no guarantee in which order the subscriber will receive the streams.
They might get the audio-only stream first, in which case they'd see a stream with audio but no video.

The official Opentok docs do recommend the latter option

**Comment by enricop89** [comment]
@CarlosTrapet Thanks for the comment. What I meant with option 1 is a classic videoconference use-case where you have: 

1. Join the video call with microphone and camera streams
2. A screen share button which will trigger the `initPublisher('publisher', {videoSource: "screen"})`

Hope that is clearer now

**Comment by enricop89** [comment]
Sample code for Option 1: https://github.com/nexmo-se/opentok-react-screenshare-sample

**Comment by renege** [comment]
@enricop89 This solves the issue that you can add the Microphone as the audio source, but how can I add the "real audio" from the shared screen to the audioSource? For example: you are sharing your screen with a powerpoint, which has a video with sound. How can I let the viewers hear that sound? 
We have an App where there are two published windows; one for webcam + audio and one for screen + audio (from the screen, but that doesnt' work).
This happens a lot in our app. Now people let the sound hear via their microphone, out of the laptop speakers.

**Comment by enricop89** [comment]
@renege in this case you need to use [getDisplayMedia](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia). To use it with our SDK, you would need to use a customer `audioSource` and `videoSource`.

Please check sample code here: https://gist.github.com/enricop89/6b69b32c4d978d59f375a9e825ea0196

**Comment by renege** [comment]
@enricop89 
Not working like expected. This results in an empty Array for the AudioTracks:
```
const promise = Promise.all([
    navigator.mediaDevices.getDisplayMedia({
        video: true,
        audio: true
    })
]).then(([stream]) => {
    console.info(stream.getAudioTracks());
```
Testing in Chrome, both MacOS and Windows

**Comment by enricop89** [comment]
@renege you can only share audio when you select a tab in Chrome, it's not possible to share audio from an external application (ie, powerpoint). It's a browser limitation.
