### ISSUE TITLE
Get and update width and height of publisher and subscriber's screen

### ISSUE THREAD

**Issue by Oxair** [opentok/opentok-react#85]
Can you please tell, how to get and update the publisher's video dimension coming **on** the subscriber's screen if the publisher changes his orientation from portrait to landscape or vice versa.
The stream object is currently returning static width and height of : 640 x 480 as shown in image below.

![Screen Shot 2019-12-06 at 12 12 08 PM](https://user-images.githubusercontent.com/31743806/70303660-029cb300-1822-11ea-81e5-f2cfd45b97d9.png)

**Comment by enricop89** [comment]
Hey @Oxair, you can use the `videoDimensionsChanged` event. 

Example: 

```
this.subscriberEventHandlers = {
			videoDimensionsChanged: (event) => {
				console.log('videoDimensionsChanged', event);
			}
		};

<OTSubscriber
  eventHandlers={this.subscriberEventHandlers}
/>
```

Hope it helps!
