### ISSUE TITLE
OT_TIMEOUT Session.publish :: Could not publish in a reasonable amount of time

### ISSUE THREAD

**Issue by SureshSc** [opentok/opentok-react#92]
**../node_modules/@opentok/client/dist/js/opentok.js:17105:66 . onPublishingTimeout**

Getting OT_TIMEOUT happened in Win 8, Chrome 79.0.3945.

How to catch/handle this issue?

<img width="962" alt="Screenshot 2020-02-07 at 11 31 17 AM" src="https://user-images.githubusercontent.com/5052940/74005041-a0853900-499d-11ea-9baf-c85a3eddf1ba.png">

**Comment by vinhnglx** [comment]
I think this library has stopped maintenance, I think. If you want to catch/handle the error, I highly recommend using the [official OpenJS client](https://www.npmjs.com/package/@opentok/client).
fyi, I have re-wrote all my components using the OpenJS client library.

**Comment by inlightmedia** [comment]
We just started to see this issue become a problem as well.

**Comment by enricop89** [comment]
@SureshSc you can use https://github.com/opentok/opentok-react#otpublisher-component onError method to catch those errors. 

Something like: 

```
class App extends React.Component {
	constructor(props) {
		super(props);
this.publisherEventHandlers = {
			accessDenied: () => {
				console.log('User denied access to media source');
			},
			streamCreated: () => {
				console.log('Publisher stream created');
			},
			streamDestroyed: ({ reason }) => {
				console.log(`Publisher stream destroyed because: ${reason}`);
			},
		};
}

onPublishError = error => {
		this.setState({ error });
};

render() {
		const { apiKey, sessionId, token } = this.props.credentials;
		const { error, connection, publishVideo } = this.state;
		return (
			<div>
				<div id="sessionStatus">Session Status: {connection}</div>
				<button onClick={this.disconnectSession}>Disconnect</button>
				{error ? (
					<div className="error">
						<strong>Error:</strong> {error}
					</div>
				) : null}
				<OTSession
					apiKey={apiKey}
					sessionId={sessionId}
					token={token}
					ref={this.otSession}
					onError={this.onSessionError}
					eventHandlers={this.sessionEventHandlers}
				>
					<OTPublisher
						properties={{ publishVideo, width: 200, height: 200 }}
						onPublish={this.onPublish}
						onError={this.onPublishError}
						eventHandlers={this.publisherEventHandlers}
					/>
				</OTSession>
			</div >
		);
	}

```
Let me know if it works.

**Comment by nish9142** [comment]
@enricop89  the above code block only helps to catch but how should we handle it.
