### ISSUE TITLE
detect the first publisher

### ISSUE THREAD

**Issue by eliransu** [opentok/opentok-react#95]
Hi,
I'm trying to create an application that acts like main publisher (1) and rest publishers (n-1),
there is any option to detect the first publisher (1) (we need to detect him as a peer Subscriber)? 
I want to draw the main publisher at the top of the screen while the others (n-1) will be at the bottom (for all of them).

hope you understand what im trying todo

thanks!

**Comment by enricop89** [comment]
You can leverage the session's events, such as https://github.com/opentok/opentok-react#createsession-helper or publisher events https://github.com/opentok/opentok-react#otpublisher-component

We don't have any concept of "first publisher" in opentok. We have a session, which is a virtual room, where people can publish their stream or subscribe to other people's stream. 

Using the above events, you can build your own logic to detect the first publisher
